#lang racket/base
;; Generates `lib/column/parity_test.mbt`.
;;
;; The column algebra is the subtlest code in the port and the least covered by
;; real input: the 612 `.rhm` files in the reference tree contain no tabs at
;; all, so nothing in the corpus would ever exercise the partial order or reach
;; the incomparable case. These probes are the coverage.
;;
;; Every column is built the way the lexer builds one -- by running
;; `count-graphemes` over a piece of text -- and then compared against every
;; other with the reference's own comparators, INCLUDING whether the comparison
;; reached the incomparable branch. That last bit is the point: a port that
;; answers `#f` where the reference raises "incomparable indentation due to
;; mixed tabs" is wrong in a way no `<` or `>` assertion would notice.
;;
;;   racket tools/gen-column-tests.rkt        (or: just column-regen)

(require racket/string racket/list
         (file "../reference/shrubbery-lib/shrubbery/private/column.rkt"))

(define out-path "lib/column/parity_test.mbt")

;; Text whose columns cover: no tabs, tabs only, tabs after characters,
;; characters after tabs, and the prefix relationships between them. The
;; grapheme cases are there so the "one per cluster, not one per code point"
;; rule is exercised at the same time.
(define texts
  (list ""
        " "
        "  "
        "   "
        "\t"
        "\t\t"
        " \t"
        "  \t"
        " \t "
        " \t  "
        "\t "
        "\t  "
        "\t \t"
        "\t\t "
        "  \t \t "
        "ab"
        "ab\t"
        "\tab"
        "á"          ; one cluster, two code points
        "\U0001F468‍\U0001F469‍\U0001F466"))

;; Each probe is a text plus whether the `|` half-column is added on top.
(define probes
  (for*/list ([t (in-list texts)] [half (in-list '(#f #t))])
    (list t half)))

(define (column-of t half)
  (define-values (lines col) (count-graphemes t))
  (if half (column+ 0.5 col) col))

(define (mbt-string s)
  (string-append "\""
                 (apply string-append
                        (for/list ([ch (in-string s)])
                          (format "\\u{~x}" (char->integer ch))))
                 "\""))

;; 0 = false, 1 = true, 2 = the reference reached its incomparable branch.
(define (answer op c1 c2)
  (define hit #f)
  (define v (op c1 c2 #:incomparable (lambda () (set! hit #t) #f)))
  (if hit 2 (if v 1 0)))

(define (main)
  (call-with-output-file out-path #:exists 'replace
    (lambda (o)
      (fprintf o "// Generated by tools/gen-column-tests.rkt from Racket ~a and the\n" (version))
      (fprintf o "// reference's private/column.rkt. DON'T EDIT IT -- run\n")
      (fprintf o "// `just column-regen` and review the diff.\n\n")
      (fprintf o "///|\n")
      (fprintf o "/// Each probe is a piece of text and whether the `|` half-column is\n")
      (fprintf o "/// added on top of the column it produces.\n")
      (fprintf o "let probes : Array[(String, Bool)] = [\n")
      (for ([p (in-list probes)])
        (fprintf o "  (~a, ~a),\n" (mbt-string (car p)) (if (cadr p) "true" "false")))
      (fprintf o "]\n\n")
      (fprintf o "///|\n")
      (fprintf o "/// `[lt, gt, eq]` for every ordered pair of probes, row-major.\n")
      (fprintf o "/// 0 is false, 1 is true, 2 is \"the reference called this incomparable\".\n")
      (fprintf o "let answers : FixedArray[Int] = [\n")
      (for* ([p1 (in-list probes)])
        (fprintf o "  ")
        (for ([p2 (in-list probes)])
          (define c1 (column-of (car p1) (cadr p1)))
          (define c2 (column-of (car p2) (cadr p2)))
          (fprintf o "~a, ~a, ~a, "
                   (answer column<? c1 c2)
                   (answer column>? c1 c2)
                   (answer column=? c1 c2)))
        (fprintf o "\n"))
      (fprintf o "]\n\n")
      ;; `column-` is separate: it is a number, not a comparison.
      (fprintf o "///|\n")
      (fprintf o "/// `column-` for every ordered pair, in half-columns.\n")
      (fprintf o "let differences : FixedArray[Int] = [\n")
      (for ([p1 (in-list probes)])
        (fprintf o "  ")
        (for ([p2 (in-list probes)])
          (define c1 (column-of (car p1) (cadr p1)))
          (define c2 (column-of (car p2) (cadr p2)))
          (fprintf o "~a, " (inexact->exact (round (* 2 (column- c1 c2))))))
        (fprintf o "\n"))
      (fprintf o "]\n\n")
      (fprintf o #<<MBT
///|
/// Build a column the way the lexer does: by walking text.
fn column_of(probe : (String, Bool)) -> @column.Column {
  let (text, half) = probe
  let (_, col) = @column.count_graphemes(text)
  if half {
    col.half_up()
  } else {
    col
  }
}

///|
/// What the reference would have answered for one comparison.
fn expected(code : Int) -> String {
  match code {
    0 => "false"
    1 => "true"
    _ => "incomparable"
  }
}

///|
/// How our four-way answer reads as one of the reference's three codes.
fn actual(order : @column.ColumnOrder, want : @column.ColumnOrder) -> String {
  match order {
    Incomparable => "incomparable"
    _ => if order == want { "true" } else { "false" }
  }
}

///|
test "every comparison agrees with the reference, incomparability included" {
  let n = probes.length()
  for i in 0..<n {
    let c1 = column_of(probes[i])
    for j in 0..<n {
      let c2 = column_of(probes[j])
      let base = (i * n + j) * 3
      let order = c1.cmp(c2)
      let checks : Array[(Int, @column.ColumnOrder)] = [
        (0, Lt),
        (1, Gt),
        (2, Eq),
      ]
      for check in checks {
        let (k, want) = check
        let got = actual(order, want)
        let should = expected(answers[base + k])
        if got != should {
          fail(
            "probe \{i} vs \{j}: \{want.name()} should be \{should}, got \{got}",
          )
        }
      }
    }
  }
}

///|
test "differences agree with the reference" {
  let n = probes.length()
  for i in 0..<n {
    let c1 = column_of(probes[i])
    for j in 0..<n {
      let c2 = column_of(probes[j])
      let want = differences[i * n + j]
      let got = c1.sub(c2)
      if got != want {
        fail("probe \{i} - \{j}: want \{want} half-columns, got \{got}")
      }
    }
  }
}

MBT
               )))
  (printf "~a written: ~a probes, ~a comparisons\n"
          out-path (length probes) (* (length probes) (length probes) 3)))

(main)
