#!/usr/bin/env python3
"""Generate `html/names/entities.mbt` from the WHATWG named character references.

The list is data the specification publishes as JSON, and it is 2,231 entries
long -- every one of them, with and without the trailing `;`, because HTML
resolves `&amp` as well as `&amp;` and a parser that knew only one of the two
spellings would be wrong on a large fraction of the real web.

The table is emitted as ONE string rather than as an array of 4,462 string
literals: a literal array that size is slow to compile and enormous in the
generated code, while a single string is one constant split once at startup.
U+0001 separates the records and U+0002 the two fields; no named reference
resolves to either, which is checked here rather than assumed.  A newline or a
tab could NOT have been used as the separator, and that is not hypothetical:
`&NewLine;` and `&Tab;` resolve to exactly those.

    just entities-regen        # refetch and rewrite, then review the diff
"""

import json
import sys

SOURCE = "https://html.spec.whatwg.org/entities.json"

REC = "\u0001"
FLD = "\u0002"

# How much escaped text to put on one source line. The generated file is read
# by people looking for one reference, so the lines have to stay finite.
LINE_BUDGET = 900


def escape(s):
    """A MoonBit string literal body: ASCII as itself, everything else escaped."""
    buf = []
    for ch in s:
        o = ord(ch)
        if ch == '"':
            buf.append('\\"')
        elif ch == "\\":
            buf.append("\\\\")
        elif 0x20 <= o < 0x7F:
            buf.append(ch)
        else:
            buf.append("\\u{%X}" % o)
    return "".join(buf)


def main():
    if len(sys.argv) < 3:
        print("usage: gen-entities.py ENTITIES_JSON OUTPUT_MBT", file=sys.stderr)
        return 2
    src, out = sys.argv[1], sys.argv[2]
    with open(src, encoding="utf-8") as f:
        data = json.load(f)

    records = []
    for name, entry in sorted(data.items()):
        assert name.startswith("&"), name
        value = entry["characters"]
        assert REC not in value and FLD not in value, name
        records.append((name[1:], value))

    longest = max(len(n) for n, _ in records)

    # Pack, then break into lines at record boundaries so that a diff on one
    # reference touches one line.
    lines, cur, size = [], [], 0
    for name, value in records:
        rec = name + FLD + value
        e = escape(rec)
        if cur and size + len(e) > LINE_BUDGET:
            lines.append(REC.join(cur))
            cur, size = [], 0
        cur.append(rec)
        size += len(e) + 6
    if cur:
        lines.append(REC.join(cur))

    with open(out, "w", encoding="utf-8") as f:
        f.write(
            "// Generated by tools/gen-entities.py from\n"
            "// %s -- %d named references.\n"
            "// DON'T EDIT IT -- run `just entities-regen` and review the diff.\n\n"
            % (SOURCE, len(records))
        )
        f.write(
            "///|\n"
            "/// The longest named reference, in code units and without the `&`.\n"
            "///\n"
            "/// The decoder tries substrings from this length downwards, because the\n"
            "/// specification's rule is longest-match: `&notin;` is one reference and\n"
            "/// `&not;` followed by `in;` is another, and only the length says which.\n"
            "pub let longest_reference : Int = %d\n\n" % longest
        )
        f.write(
            "///|\n"
            "/// Every named reference, packed as one string.\n"
            "///\n"
            "/// Records are separated by U+0001, and each record is a name, U+0002, and\n"
            "/// the replacement. Neither separator can occur in a replacement, which the\n"
            "/// generator asserts rather than assumes.\n"
            "pub let packed_references : String =\n"
        )
        last = len(lines) - 1
        for i, line in enumerate(lines):
            body = escape(line if i == 0 else REC + line)
            f.write('  "%s"%s\n' % (body, "" if i == last else " +"))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
